# Generated by Django 4.2.19 on 2025-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('student_location', models.CharField(max_length=40)),
                ('student_phone_number', models.CharField(max_length=40)),
            ],
        ),
    ]
