# Generated by Django 4.2.19 on 2025-02-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.region'),
        ),
    ]
