# Generated by Django 4.2.19 on 2025-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_region_alter_student_details_student_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Location',
        ),
    ]
