# Generated by Django 4.2.19 on 2025-02-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_rename_region_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.phone_number'),
        ),
    ]
