# Generated by Django 4.2.19 on 2025-02-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.location')),
            ],
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_location',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_phone_number',
        ),
        migrations.DeleteModel(
            name='Phone_number',
        ),
        migrations.DeleteModel(
            name='student_details',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='mobile_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.studentdetails'),
        ),
    ]
