# Generated by Django 4.2.19 on 2025-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_phonenumber_studentdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='masked_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
