# Generated by Django 4.2.19 on 2025-02-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_phonenumber_masked_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='masked_number',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='student_phone_number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='student_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.studentdetails'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='masked_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
