# Generated by Django 4.2.19 on 2025-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_phonenumber_masked_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=20)),
                ('student_count', models.IntegerField()),
                ('program_message', models.CharField(max_length=30)),
                ('program_document', models.FileField(upload_to='student_updates/media')),
            ],
        ),
    ]
