# Generated by Django 4.2.19 on 2025-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_programinfo_program_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programinfo',
            name='program_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
