# Generated by Django 4.2.19 on 2025-03-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_programinfo_program_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinfo',
            name='program_date',
        ),
    ]
