# Generated by Django 4.2.19 on 2025-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_remove_programinfo_program_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programinfo',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
