# Generated by Django 4.2.19 on 2025-03-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_programinfo_phone_number_programinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinfo',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='programinfo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='programinfo',
            name='program_time',
        ),
        migrations.AddField(
            model_name='programinfo',
            name='program_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CampaignDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('delivery_time', models.TimeField(null=True)),
                ('campaign_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.programinfo')),
            ],
        ),
    ]
