# Generated by Django 4.2.19 on 2025-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_remove_programinfo_added_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinfo',
            name='program_status',
        ),
    ]
