# Generated by Django 4.2.19 on 2025-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_remove_programinfo_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='program_document',
            field=models.FileField(blank=True, null=True, upload_to='student_updates/media'),
        ),
    ]
