# Generated by Django 4.2.19 on 2025-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0018_alter_programinfo_program_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='programinfo',
            name='selected_ids',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
