# Generated by Django 4.2.19 on 2025-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0019_programinfo_selected_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='selected_ids',
            field=models.CharField(max_length=255),
        ),
    ]
