# Generated by Django 4.2.19 on 2025-03-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0020_alter_programinfo_selected_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigndetails',
            old_name='campaign_name',
            new_name='campaign',
        ),
        migrations.RemoveField(
            model_name='programinfo',
            name='selected_ids',
        ),
    ]
